### ISSUE TITLE
addIV() needs merge option removed, rename to expandIV()

### ISSUE THREAD

**Issue by mvdm** [mvdm/vandermeerlab#37]
check which functions rely on addIV() and change to expandIV()!

**Comment by aacarey** [comment]
if ExpandIV can also contract the intervals, some general names might be:

- ResizeIV 
- RedefineIV
- AlterIV
- ?

**Comment by mvdm** [comment]
good idea, +1 for ResizeIV

**Comment by emirvine** [comment]
I like resizeIV too, it emphasizes that it could be expanded or shrunk.
