### ISSUE TITLE
intersectIV() needs to have options for time-based and unit-based intersects

### ISSUE THREAD

**Issue by mvdm** [mvdm/vandermeerlab#39]
right now, only does "unit-based" intersect, ie keeps entire interval in input1 if a piece of input2 is inside it

however need use case for keeping only piece of input1 that actually overlaps with input2.

**Comment by emirvine** [comment]
I'm planning on implementing these as separate functions, renaming the IntersectIV() to OverlapIV() and then making a separate IntersectIV() function which will return the interval that intersects (in time) of two intervals. Does that make sense? I see these things as pretty separate operations, so I think doing it within the same function doesn't make too much sense. But will it be too confusing to have the same name as the (old) IntersectIV function?

**Comment by mvdm** [comment]
I don't have any strong preference for splitting or lumping the two use cases -- from a pure functionality perspective -- but I would like to avoid the proliferation of IV-related function names that made it hard to figure out what is doing what. If we can come up with good descriptive function names for two different functions I'm OK with splitting... maybe "UnitIntersectIV()" and "TimeIntersectIV()", but is unwieldy...

A further consideration is that I can imagine more options down the line, which may not assign cleanly to one or the other, once the functions are split...

Thoughts, @youkitan, @aacarey?

**Comment by aacarey** [comment]
aacarey's actual thoughts: "Ahh I don't know what these things mean."

I don't really have anything constructive to say, only that the function should maybe do what its name describes (if that name is a math term like "intersect" it should do a true intersection)?  If it does more than its name describes, maybe it should have a term that encompasses as much of what it does as possible?
