### ISSUE TITLE
Handling ExpKeys in a variable's cfg.ExpKeys field

### ISSUE THREAD

**Issue by aacarey** [mvdm/vandermeerlab#42]
LoadCSC, LoadPos and LoadSpikes add ExpKeys to their outputs: var_out.cfg.ExpKeys = ExpKeys. In some cases this means that ExpKeys will be loaded 4 or more times for a single session (like generating candidate events that have a couple of CSCs loaded, position data and spikes). 
Maybe an improved way may might be having the user do LoadExpKeys then var_out = AddExpKeys(var_in,ExpKeys) so that the action of loading the keys is done only once rather than 4 times, and only if the user intends on using the ExpKeys from inside the variable for something down the line. Otherwise we could have a default field that is AddExpkeys = 0 so that we can suppress the action when ExpKeys aren't needed inside the variable.

**Comment by mvdm** [comment]
I like handling this in the cfg, but how about having the default be to 
load the ExpKeys? I think the overhead (time loading) should be small, 
but then if you really care you can override it to not load.
